# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Impute"); Pkg.test("Impute"; coverage=true)'
after_success:
  - |
      julia -e '
        VERSION >= v"0.7.0-DEV.3656" && using Pkg
        VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Impute"))
        Pkg.add("Coverage")
        using Coverage
        Codecov.submit(Codecov.process_folder())
      '
  - |
      julia -e '
        VERSION >= v"0.7.0-DEV.3656" && using Pkg
        VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Impute"))
        Pkg.add("Documenter")
        include(joinpath("docs", "make.jl"))
      '
